export const ROUTES = {
  StartScreen: 'start',
  AuthScreen: 'auth',
  LoginScreen: 'login',
  RegisterScreen: 'register',
  PhoneInputScreen: 'phone-input',
  VerifyCodeScreen: 'verify-code',
  HomeScreen: 'home',
  ProfileScreen: 'profile',
  TabScreen: 'tab',
  OnboardingScreen: 'onboarding',
  BirthScreen: 'birth',
  FamilyNumberScreen: 'family-number',
  GenderScreen: 'gender',
  RelationshipScreen: 'relationship',
  SuccessSignupScreen: 'success-signup',
  VehicleScreen: 'vehicle',
  MessageScreen: 'message',
};
