export const ROUTES = {
  StartScreen: 'start',
  AuthScreen: 'auth',
  LoginScreen: 'login',
  RegisterScreen: 'register',
  PhoneInputScreen: 'phone-input',
  VerifyCodeScreen: 'verify-code',
  HomeScreen: 'home',
  ProfileScreen: 'profile',
  TabScreen: 'tab',
  OnboardingScreen: 'onboarding',
  BirthScreen: 'birth',
  FamilyNumberScreen: 'family-number',
  GenderScreen: 'gender',
  RelationshipScreen: 'relationship',
  SuccessSignupScreen: 'success-signup',
  VehicleScreen: 'vehicle',
  MessageScreen: 'message',
  BlockM_1_Screen: 'blockm-1',
  BlockM_2_Screen: 'blockm-2',
  BlockM_3_Screen: 'blockm-3',
  BlockM_4_Screen: 'blockm-4',
  BlockM_5_Screen: 'blockm-5',
  EditProfileScreen: 'edit-profile',
  LanguageScreen: 'language',
  PrivacyPolicyScreen: 'privacy-policy',
  DrawerScreen: 'drawer',
};
